#!/usr/bin/env python3
"""Analyze logs generated by the experiments and organize results."""

import json
from pathlib import Path

import matplotlib.pyplot as plt

CURRENT_DIR = Path(__file__).parent
RESULTS_DIR = CURRENT_DIR / "results"
PLOTS_DIR = CURRENT_DIR / "plots"

PLOTS_DIR.mkdir(exist_ok=True)


def get_params(key):
    items = key.split("-")
    if items[1] == "sharegpt":
        return dict(
            batch_size=items[0],
            dataset="sharegpt",
            sparse_kv_cache_method=items[3],
            sparse_kv_cache_budget="max"
            if items[4] == "max" else int(items[4]),
            sparse_kv_cache_num_per_evict=int(items[5]),
            sparse_kv_cache_internal="-".join(items[6:]),
        )
    raise NotImplementedError


def main():
    with (RESULTS_DIR / "analyze.json").open("r", encoding="utf-8") as f:
        results = json.load(f)

    keys = [get_params(key) for key in results]
    throughputs = [item["__request_throughput__"] for item in results.values()]
    plt.bar(["-".join(str(it) for it in key.values()) for key in keys],
            throughputs)
    plt.xticks(rotation=90, fontsize=8)
    plt.tight_layout()
    plt.savefig(PLOTS_DIR / "throughputs.png")


if __name__ == "__main__":
    main()
